# Basic Python

## 1. Split this string

Output should be a List: ['Hi', 'there', 'Sam!']

In [1]:
s = "Hi there Sam!"

In [2]:
s.partition("there")

('Hi ', 'there', ' Sam!')

## 2. Use .format() to print the following string. 

 Output should be: The diameter of Earth is 12742 kilometers.

In [1]:
planet = "Earth"
diameter = 12742

In [7]:
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [35]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [36]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [48]:
ten_zero_arr=np.zeros(10)  #An array having 10 zeros
print(ten_zero_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [49]:
ten_five_arr=np.ones(10)*5   #An array which contains 10 fives
print(ten_five_arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [78]:
r=np.arange(20,35)  #creating a range

j=0
even_arr=np.arange(20,35) #An array to store the even values from the range


for i in r:
    if i % 2==0:
        even_arr[j]=i
        j=j+1
    else:
        continue
        
    
    
print(even_arr)

[20 22 24 26 28 30 32 34 28 29 30 31 32 33 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [81]:
arr=np.arange(0,9)
arr

arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [98]:
a=np.array([[1,2,3]])    #row wise concatenation
b=np.array([[4,5,6]])

np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [2]:
import pandas as pd


In [107]:
height={'Bijoy':160,'Arun':170,'Roy':175}          #height in centimeter
weight={'Bijoy':70,'Arun':60,'Roy':85}             #weight in Kilogram

Data_f=pd.DataFrame({'Height':height,'Weight':weight})
Data_f



Height  Weight
Bijoy     160      70
Arun      170      60
Roy       175      85

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [5]:
import pandas as pd
from datetime import date, timedelta
sdate = date(2023,1,1)   # start date
edate = date(2023,2,10)   # end date
pd.date_range(sdate,edate-timedelta(days=1),freq='d')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]